FROM python:3.10-slim

WORKDIR /workspace

RUN pip install --no-cache-dir streamlit requests

COPY app_ui.py .

EXPOSE 8501

CMD ["streamlit", "run", "app_ui.py", "--server.port=8501", "--server.address=0.0.0.0"]